/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const snapshot = [
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text455797646',
            max: 0,
            min: 0,
            name: 'collectionRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text127846527',
            max: 0,
            min: 0,
            name: 'recordRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text1582905952',
            max: 0,
            min: 0,
            name: 'method',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: true,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: true,
            type: 'autodate',
          },
        ],
        id: 'pbc_2279338944',
        indexes: ['CREATE INDEX `idx_mfas_collectionRef_recordRef` ON `_mfas` (collectionRef,recordRef)'],
        listRule: "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        name: '_mfas',
        system: true,
        type: 'base',
        updateRule: null,
        viewRule: "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
      },
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text455797646',
            max: 0,
            min: 0,
            name: 'collectionRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text127846527',
            max: 0,
            min: 0,
            name: 'recordRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cost: 8,
            hidden: true,
            id: 'password901924565',
            max: 0,
            min: 0,
            name: 'password',
            pattern: '',
            presentable: false,
            required: true,
            system: true,
            type: 'password',
          },
          {
            autogeneratePattern: '',
            hidden: true,
            id: 'text3866985172',
            max: 0,
            min: 0,
            name: 'sentTo',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: true,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: true,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: true,
            type: 'autodate',
          },
        ],
        id: 'pbc_1638494021',
        indexes: ['CREATE INDEX `idx_otps_collectionRef_recordRef` ON `_otps` (collectionRef, recordRef)'],
        listRule: "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        name: '_otps',
        system: true,
        type: 'base',
        updateRule: null,
        viewRule: "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
      },
      {
        createRule: null,
        deleteRule: "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text455797646',
            max: 0,
            min: 0,
            name: 'collectionRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text127846527',
            max: 0,
            min: 0,
            name: 'recordRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text2462348188',
            max: 0,
            min: 0,
            name: 'provider',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text1044722854',
            max: 0,
            min: 0,
            name: 'providerId',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: true,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: true,
            type: 'autodate',
          },
        ],
        id: 'pbc_2281828961',
        indexes: ['CREATE UNIQUE INDEX `idx_externalAuths_record_provider` ON `_externalAuths` (collectionRef, recordRef, provider)', 'CREATE UNIQUE INDEX `idx_externalAuths_collection_provider` ON `_externalAuths` (collectionRef, provider, providerId)'],
        listRule: "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        name: '_externalAuths',
        system: true,
        type: 'base',
        updateRule: null,
        viewRule: "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
      },
      {
        createRule: null,
        deleteRule: "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text455797646',
            max: 0,
            min: 0,
            name: 'collectionRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text127846527',
            max: 0,
            min: 0,
            name: 'recordRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text4228609354',
            max: 0,
            min: 0,
            name: 'fingerprint',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: true,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: true,
            type: 'autodate',
          },
        ],
        id: 'pbc_4275539003',
        indexes: ['CREATE UNIQUE INDEX `idx_authOrigins_unique_pairs` ON `_authOrigins` (collectionRef, recordRef, fingerprint)'],
        listRule: "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        name: '_authOrigins',
        system: true,
        type: 'base',
        updateRule: null,
        viewRule: "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
      },
      {
        authAlert: {
          emailTemplate: {
            body: "<p>Hello,</p>\n<p>We noticed a login to your {APP_NAME} account from a new location:</p>\n<p><em>{ALERT_INFO}</em></p>\n<p><strong>If this wasn't you, you should immediately change your {APP_NAME} account password to revoke access from all other locations.</strong></p>\n<p>If this was you, you may disregard this email.</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
            subject: 'Login from a new location',
          },
          enabled: true,
        },
        authRule: '',
        authToken: {
          duration: 86400,
        },
        confirmEmailChangeTemplate: {
          body: '<p>Hello,</p>\n<p>Click on the button below to confirm your new email address.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-email-change/{TOKEN}" target="_blank" rel="noopener">Confirm new email</a>\n</p>\n<p><i>If you didn\'t ask to change your email address, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Confirm your {APP_NAME} new email address',
        },
        createRule: null,
        deleteRule: null,
        emailChangeToken: {
          duration: 1800,
        },
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cost: 0,
            hidden: true,
            id: 'password901924565',
            max: 0,
            min: 8,
            name: 'password',
            pattern: '',
            presentable: false,
            required: true,
            system: true,
            type: 'password',
          },
          {
            autogeneratePattern: '[a-zA-Z0-9]{50}',
            hidden: true,
            id: 'text2504183744',
            max: 60,
            min: 30,
            name: 'tokenKey',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            exceptDomains: null,
            hidden: false,
            id: 'email3885137012',
            name: 'email',
            onlyDomains: null,
            presentable: false,
            required: true,
            system: true,
            type: 'email',
          },
          {
            hidden: false,
            id: 'bool1547992806',
            name: 'emailVisibility',
            presentable: false,
            required: false,
            system: true,
            type: 'bool',
          },
          {
            hidden: false,
            id: 'bool256245529',
            name: 'verified',
            presentable: false,
            required: false,
            system: true,
            type: 'bool',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: true,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: true,
            type: 'autodate',
          },
        ],
        fileToken: {
          duration: 180,
        },
        id: 'pbc_3142635823',
        indexes: ['CREATE UNIQUE INDEX `idx_tokenKey_pbc_3142635823` ON `_superusers` (`tokenKey`)', "CREATE UNIQUE INDEX `idx_email_pbc_3142635823` ON `_superusers` (`email`) WHERE `email` != ''"],
        listRule: null,
        manageRule: null,
        mfa: {
          duration: 1800,
          enabled: false,
          rule: '',
        },
        name: '_superusers',
        oauth2: {
          enabled: false,
          mappedFields: {
            avatarURL: '',
            id: '',
            name: '',
            username: '',
          },
        },
        otp: {
          duration: 180,
          emailTemplate: {
            body: "<p>Hello,</p>\n<p>Your one-time password is: <strong>{OTP}</strong></p>\n<p><i>If you didn't ask for the one-time password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
            subject: 'OTP for {APP_NAME}',
          },
          enabled: false,
          length: 8,
        },
        passwordAuth: {
          enabled: true,
          identityFields: ['email'],
        },
        passwordResetToken: {
          duration: 1800,
        },
        resetPasswordTemplate: {
          body: '<p>Hello,</p>\n<p>Click on the button below to reset your password.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-password-reset/{TOKEN}" target="_blank" rel="noopener">Reset password</a>\n</p>\n<p><i>If you didn\'t ask to reset your password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Reset your {APP_NAME} password',
        },
        system: true,
        type: 'auth',
        updateRule: null,
        verificationTemplate: {
          body: '<p>Hello,</p>\n<p>Thank you for joining us at {APP_NAME}.</p>\n<p>Click on the button below to verify your email address.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-verification/{TOKEN}" target="_blank" rel="noopener">Verify</a>\n</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Verify your {APP_NAME} email',
        },
        verificationToken: {
          duration: 259200,
        },
        viewRule: null,
      },
      {
        authAlert: {
          emailTemplate: {
            body: "<p>Hello,</p>\n<p>We noticed a login to your {APP_NAME} account from a new location:</p>\n<p><em>{ALERT_INFO}</em></p>\n<p><strong>If this wasn't you, you should immediately change your {APP_NAME} account password to revoke access from all other locations.</strong></p>\n<p>If this was you, you may disregard this email.</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
            subject: 'Login from a new location',
          },
          enabled: true,
        },
        authRule: '',
        authToken: {
          duration: 604800,
        },
        confirmEmailChangeTemplate: {
          body: '<p>Hello,</p>\n<p>Click on the button below to confirm your new email address.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-email-change/{TOKEN}" target="_blank" rel="noopener">Confirm new email</a>\n</p>\n<p><i>If you didn\'t ask to change your email address, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Confirm your {APP_NAME} new email address',
        },
        createRule: '',
        deleteRule: 'id = @request.auth.id',
        emailChangeToken: {
          duration: 1800,
        },
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cost: 0,
            hidden: true,
            id: 'password901924565',
            max: 0,
            min: 8,
            name: 'password',
            pattern: '',
            presentable: false,
            required: true,
            system: true,
            type: 'password',
          },
          {
            autogeneratePattern: '[a-zA-Z0-9]{50}',
            hidden: true,
            id: 'text2504183744',
            max: 60,
            min: 30,
            name: 'tokenKey',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            exceptDomains: null,
            hidden: false,
            id: 'email3885137012',
            name: 'email',
            onlyDomains: null,
            presentable: false,
            required: true,
            system: true,
            type: 'email',
          },
          {
            hidden: false,
            id: 'bool1547992806',
            name: 'emailVisibility',
            presentable: false,
            required: false,
            system: true,
            type: 'bool',
          },
          {
            hidden: false,
            id: 'bool256245529',
            name: 'verified',
            presentable: false,
            required: false,
            system: true,
            type: 'bool',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text1579384326',
            max: 255,
            min: 0,
            name: 'name',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            hidden: false,
            id: 'file376926767',
            maxSelect: 1,
            maxSize: 0,
            mimeTypes: ['image/jpeg', 'image/png', 'image/svg+xml', 'image/gif', 'image/webp'],
            name: 'avatar',
            presentable: false,
            protected: false,
            required: false,
            system: false,
            thumbs: null,
            type: 'file',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        fileToken: {
          duration: 180,
        },
        id: '_pb_users_auth_',
        indexes: ['CREATE UNIQUE INDEX `idx_tokenKey__pb_users_auth_` ON `users` (`tokenKey`)', "CREATE UNIQUE INDEX `idx_email__pb_users_auth_` ON `users` (`email`) WHERE `email` != ''"],
        listRule: 'id = @request.auth.id',
        manageRule: null,
        mfa: {
          duration: 1800,
          enabled: false,
          rule: '',
        },
        name: 'users',
        oauth2: {
          enabled: false,
          mappedFields: {
            avatarURL: 'avatar',
            id: '',
            name: 'name',
            username: '',
          },
        },
        otp: {
          duration: 180,
          emailTemplate: {
            body: "<p>Hello,</p>\n<p>Your one-time password is: <strong>{OTP}</strong></p>\n<p><i>If you didn't ask for the one-time password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
            subject: 'OTP for {APP_NAME}',
          },
          enabled: false,
          length: 8,
        },
        passwordAuth: {
          enabled: true,
          identityFields: ['email'],
        },
        passwordResetToken: {
          duration: 1800,
        },
        resetPasswordTemplate: {
          body: '<p>Hello,</p>\n<p>Click on the button below to reset your password.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-password-reset/{TOKEN}" target="_blank" rel="noopener">Reset password</a>\n</p>\n<p><i>If you didn\'t ask to reset your password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Reset your {APP_NAME} password',
        },
        system: false,
        type: 'auth',
        updateRule: 'id = @request.auth.id',
        verificationTemplate: {
          body: '<p>Hello,</p>\n<p>Thank you for joining us at {APP_NAME}.</p>\n<p>Click on the button below to verify your email address.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-verification/{TOKEN}" target="_blank" rel="noopener">Verify</a>\n</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Verify your {APP_NAME} email',
        },
        verificationToken: {
          duration: 259200,
        },
        viewRule: 'id = @request.auth.id',
      },
      {
        createRule: '',
        deleteRule: '',
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text1579384326',
            max: 0,
            min: 0,
            name: 'name',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_4121927529',
        indexes: ['CREATE UNIQUE INDEX `idx_2lohZBFWi7` ON `store_shelves` (`name`)'],
        listRule: '',
        name: 'store_shelves',
        system: false,
        type: 'base',
        updateRule: '',
        viewRule: '',
      },
      {
        createRule: '',
        deleteRule: '',
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text1579384326',
            max: 0,
            min: 0,
            name: 'name',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            cascadeDelete: true,
            collectionId: 'pbc_4121927529',
            hidden: false,
            id: 'relation2772917219',
            maxSelect: 1,
            minSelect: 0,
            name: 'shelf',
            presentable: false,
            required: false,
            system: false,
            type: 'relation',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_3146854971',
        indexes: ['CREATE UNIQUE INDEX `idx_d9hoc9QJr0` ON `ingredients` (`name`)'],
        listRule: '',
        name: 'ingredients',
        system: false,
        type: 'base',
        updateRule: '',
        viewRule: '',
      },
      {
        createRule: '',
        deleteRule: '',
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text1579384326',
            max: 0,
            min: 0,
            name: 'name',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text2560465762',
            max: 0,
            min: 0,
            name: 'slug',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            hidden: false,
            id: 'select1602912115',
            maxSelect: 1,
            name: 'source',
            presentable: false,
            required: true,
            system: false,
            type: 'select',
            values: ['MANGER_BOUGER', 'MARMITON', 'CUSTOM'],
          },
          {
            exceptDomains: null,
            hidden: false,
            id: 'url3309110367',
            name: 'image',
            onlyDomains: null,
            presentable: false,
            required: false,
            system: false,
            type: 'url',
          },
          {
            hidden: false,
            id: 'number3264267576',
            max: null,
            min: 0,
            name: 'preparationTime',
            onlyInt: false,
            presentable: false,
            required: false,
            system: false,
            type: 'number',
          },
          {
            hidden: false,
            id: 'number421638423',
            max: null,
            min: 0,
            name: 'bakingTime',
            onlyInt: false,
            presentable: false,
            required: false,
            system: false,
            type: 'number',
          },
          {
            hidden: false,
            id: 'number1038089153',
            max: null,
            min: 0,
            name: 'restTime',
            onlyInt: false,
            presentable: false,
            required: false,
            system: false,
            type: 'number',
          },
          {
            hidden: false,
            id: 'select3035901980',
            maxSelect: 4,
            name: 'seasons',
            presentable: false,
            required: false,
            system: false,
            type: 'select',
            values: ['WINTER', 'SPRING', 'SUMMER', 'AUTUMN'],
          },
          {
            hidden: false,
            id: 'select105650625',
            maxSelect: 1,
            name: 'category',
            presentable: false,
            required: true,
            system: false,
            type: 'select',
            values: ['STARTER', 'FULL_COURSE', 'MAIN_COURSE', 'SIDE_DISH', 'DESSERT', 'SAUCE', 'DRINK', 'OTHER'],
          },
          {
            hidden: false,
            id: 'select507320985',
            maxSelect: 1,
            name: 'nutriscore',
            presentable: false,
            required: true,
            system: false,
            type: 'select',
            values: ['A', 'B', 'C', 'D', 'E', 'UNKNOWN'],
          },
          {
            hidden: false,
            id: 'json1874629670',
            maxSize: 0,
            name: 'tags',
            presentable: false,
            required: false,
            system: false,
            type: 'json',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_842702175',
        indexes: ['CREATE UNIQUE INDEX `idx_hgKdh6HtaT` ON `recipes` (`slug`)'],
        listRule: '',
        name: 'recipes',
        system: false,
        type: 'base',
        updateRule: '',
        viewRule: '',
      },
      {
        createRule: '',
        deleteRule: '',
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cascadeDelete: true,
            collectionId: 'pbc_842702175',
            hidden: false,
            id: 'relation3666391351',
            maxSelect: 1,
            minSelect: 0,
            name: 'recipe',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            hidden: false,
            id: 'number4113142680',
            max: null,
            min: 0,
            name: 'order',
            onlyInt: false,
            presentable: false,
            required: false,
            system: false,
            type: 'number',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text1843675174',
            max: 0,
            min: 0,
            name: 'text',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_4284789913',
        indexes: [],
        listRule: '',
        name: 'steps',
        system: false,
        type: 'base',
        updateRule: '',
        viewRule: '',
      },
      {
        createRule: '',
        deleteRule: '',
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cascadeDelete: true,
            collectionId: 'pbc_842702175',
            hidden: false,
            id: 'relation3666391351',
            maxSelect: 1,
            minSelect: 0,
            name: 'recipe',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            cascadeDelete: true,
            collectionId: 'pbc_3146854971',
            hidden: false,
            id: 'relation1806661744',
            maxSelect: 1,
            minSelect: 0,
            name: 'ingredient',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            hidden: false,
            id: 'number2683508278',
            max: null,
            min: null,
            name: 'quantity',
            onlyInt: false,
            presentable: false,
            required: false,
            system: false,
            type: 'number',
          },
          {
            autogeneratePattern: '',
            hidden: false,
            id: 'text3703245907',
            max: 0,
            min: 0,
            name: 'unit',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_4122981313',
        indexes: [],
        listRule: '',
        name: 'recipe_ingredients',
        system: false,
        type: 'base',
        updateRule: '',
        viewRule: '',
      },
      {
        createRule: '',
        deleteRule: '',
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cascadeDelete: true,
            collectionId: 'pbc_842702175',
            hidden: false,
            id: 'relation3666391351',
            maxSelect: 1,
            minSelect: 0,
            name: 'recipe',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'pbc_2151843437',
        indexes: [],
        listRule: '',
        name: 'favorites',
        system: false,
        type: 'base',
        updateRule: '',
        viewRule: '',
      },
    ];

    return app.importCollections(snapshot, false);
  },
  (app) => {
    return null;
  },
);
